name: SwagLabs Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Chrome configuration for the pre-job stage
    - name: Set up Chrome and Chromedriver
      run: |
        sudo apt-get update -qq -y
        sudo apt-get install -y wget unzip fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-4-1 libnspr4 libnss3 libu2f-udev libvulkan1 libxcomposite1 libxdamage1 libxfixes3 libxkbcommon0 libxrandr2 xdg-utils
        wget -q -O chrome-linux64.zip https://bit.ly/chrome-linux64-121-0-6167-85
        unzip chrome-linux64.zip
        rm chrome-linux64.zip
        sudo mv chrome-linux64 /opt/chrome/
        sudo ln -s /opt/chrome/chrome /usr/local/bin/
        wget -q -O chromedriver-linux64.zip https://bit.ly/chromedriver-linux64-121-0-6167-85
        unzip -j chromedriver-linux64.zip chromedriver-linux64/chromedriver
        rm chromedriver-linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chrome --version
        chromedriver --version
        pip3 install selenium

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Build with Maven
    - name: Build with Maven
      run: mvn test -Dtest="org.testing.swaglabs.runner.TestRunner"

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
